FROM ubuntu:16.04
MAINTAINER Bob Van Zant <bob@veznat.com>
LABEL Description="up-to-date ubuntu environment" Vendor="Cloudtools"

RUN apt-get update && \
    apt-get install -y \
        build-essential \
        curl \
        git-core && \
    apt-get clean && \
    rm -rf /var/lib/apt

LABEL Description="up-to-date golang environment"

RUN mkdir -p /build  \
    && curl -O https://storage.googleapis.com/golang/go1.15.6.linux-amd64.tar.gz \
    && echo "3918e6cc85e7eaaa6f859f1bdbaac772e7a825b0eb423c63d3ae68b21f84b844 go1.15.6.linux-amd64.tar.gz" | sha256sum -c - \
    && tar -C /usr/local -xzf go1.15.6.linux-amd64.tar.gz \
    && rm -f go1.15.6.linux-amd64.tar.gz

ENV GOROOT_BOOTSTRAP=/usr/local/go
ENV GOROOT=/build/go-build/go
ENV PATH=/build/go-build/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/go/bin

RUN mkdir -p /build/go-build \
    && cd /build/go-build \
    && curl -o go.tar.gz -s https://storage.googleapis.com/golang/go1.15.6.src.tar.gz \
    && echo "890bba73c5e2b19ffb1180e385ea225059eb008eb91b694875dd86ea48675817 go.tar.gz" | sha256sum -c - \
    && tar -zxf go.tar.gz \
    && cd /build/go-build/go/src \
    && GOOS=darwin GOARCH=amd64 ./make.bash --no-clean 2>&1 > /dev/null ;

LABEL Description="ssh-cert-authority builder"

ENV GOPATH=/build/ssh-cert-authority/go
RUN mkdir -p $GOPATH/src/github.com/cloudtools/ssh-cert-authority
WORKDIR $GOPATH/src/github.com/cloudtools/ssh-cert-authority
